//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polib.NetCore.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polib.NetCore.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Translation of WordPress - 4.9.x - Development - Administration in French (France)
        ///# This file is distributed under the same license as the WordPress - 4.9.x - Development - Administration package.
        ///msgid &quot;&quot;
        ///msgstr &quot;&quot;
        ///&quot;PO-Revision-Date: 2018-02-05 09:23:58+0000\n&quot;
        ///&quot;MIME-Version: 1.0\n&quot;
        ///&quot;Content-Type: text/plain; charset=UTF-8\n&quot;
        ///&quot;Content-Transfer-Encoding: 8bit\n&quot;
        ///&quot;Plural-Forms: nplurals=2; plural=n &gt; 1;\n&quot;
        ///&quot;X-Generator: GlotPress/2.4.0-alpha\n&quot;
        ///&quot;Language: fr\n&quot;
        ///&quot;Project-Id-Version: WordPress - 4.9.x - Dev [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string admin_fr_FR {
            get {
                return ResourceManager.GetString("admin_fr_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #: C:\Users\hp\Documents\Visual Studio 2017\Projects\Polib.Net.Web\Polib.Net.Web\Views\Home\Index.cshtml:2
        ///msgid &quot;Home Page&quot;
        ///msgstr &quot;Page d&apos;accueil&quot;
        ///
        ///#: C:\Users\hp\Documents\Visual Studio 2017\Projects\Polib.Net.Web\Polib.Net.Web\Views\Home\Index.cshtml:17
        ///msgid &quot;Learn how to build ASP.NET apps that can run anywhere.&quot;
        ///msgstr &quot;Apprenez comment générer des applications ASP.NET qui peuvent s&apos;exécuter partout.&quot;
        ///
        ///#: C:\Users\hp\Documents\Visual Studio 2017\Projects\Polib.Net.Web\Polib.Net.Web\Views\Home [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string messages_fr_FR {
            get {
                return ResourceManager.GetString("messages_fr_FR", resourceCulture);
            }
        }
    }
}
